name: 'kubectl-with-oke'
author: jarvan1
description: kubectl OCI
branding:
  color: 'white'
  icon: 'command'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/jarvan1/oci-kubectl-action:latest'
inputs:
  oci_cli_user:
    description: OCI user
    required: true
  oci_cli_tenancy: 
    description: OCI tenancy
    required: true
  oci_cli_fingerprint:
    description: OCI key fingerprint
    required: true
  oci_cli_key_content:
    description: OCI private key
    required: true
  oci_cli_region:
    description: OCI region
    required: true
  oke_cluster_id:
    description: oke cluster id
    required: true
  args:
    description: The arguments that you want to pass through to the kubectl command
    required: true
  manifests_file:
    description: The mainfests file to deploy to K8S
    required: false
  image:
    description: The image in manifests file
    required: false
outputs:
  kubectl-out:
    description: The output of the kubectl command